/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

/**
 *
 * @author admin
 */
public class QuanLyChung extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyChung
     */
    public QuanLyChung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTables3 = new javax.swing.JButton();
        btnTables4 = new javax.swing.JButton();
        btnTables5 = new javax.swing.JButton();
        btnTables6 = new javax.swing.JButton();
        btnTables7 = new javax.swing.JButton();
        btnTables8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/Administrative Tools_50px.png"))); // NOI18N
        jLabel1.setText("Management");

        btnTables3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTables3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/Students.png"))); // NOI18N
        btnTables3.setText("Student");
        btnTables3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTables3ActionPerformed(evt);
            }
        });

        btnTables4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTables4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/score.png"))); // NOI18N
        btnTables4.setText("Score");
        btnTables4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTables4ActionPerformed(evt);
            }
        });

        btnTables5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTables5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/education.png"))); // NOI18N
        btnTables5.setText("Subject");
        btnTables5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTables5ActionPerformed(evt);
            }
        });

        btnTables6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTables6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/classroom.png"))); // NOI18N
        btnTables6.setText("Class");
        btnTables6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTables6ActionPerformed(evt);
            }
        });

        btnTables7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTables7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/sm.png"))); // NOI18N
        btnTables7.setText("Semester");
        btnTables7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTables7ActionPerformed(evt);
            }
        });

        btnTables8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTables8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiaoDien/Icon/semester.png"))); // NOI18N
        btnTables8.setText("Course");
        btnTables8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTables8ActionPerformed(evt);
            }
        });

        jMenu4.setText("Account");

        jMenuItem1.setText("Add Account");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Change Password");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTables6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTables3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTables7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTables4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTables5, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(btnTables8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTables3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTables4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTables5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTables6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTables7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTables8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
//        if (!AccountDAO.getInstance().GetAccount().getUsername().equals("admin")) {
//            JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập chức năng này!");
//            return;
//        }
//
//        ThemTaiKhoan ttk = new ThemTaiKhoan();
//        ttk.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
//        DoiMatKhau dmk = new DoiMatKhau();
//        dmk.setVisible(true);
        //        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
//        MenuDangNhap mdn = new MenuDangNhap();
//        mdn.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnTables3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTables3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTables3ActionPerformed

    private void btnTables4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTables4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTables4ActionPerformed

    private void btnTables5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTables5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTables5ActionPerformed

    private void btnTables7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTables7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTables7ActionPerformed

    private void btnTables8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTables8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTables8ActionPerformed

    private void btnTables6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTables6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTables6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyChung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyChung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTables3;
    private javax.swing.JButton btnTables4;
    private javax.swing.JButton btnTables5;
    private javax.swing.JButton btnTables6;
    private javax.swing.JButton btnTables7;
    private javax.swing.JButton btnTables8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
